### ISSUE TITLE
Resource instance link not being set in client._resources

### ISSUE THREAD

**Issue by mbiokyle29** [biosustain/potion-client#11]
As far as I can tell this is basically dead code:

``` python
if 'instances' in links:
    root = cls._instances.href
elif 'self' in links:
    root = cls._self.href[:cls._self.href.rfind('/')]
```

The only time `links` or `cls_links` is modified is when `link.rel` is explicitly not "self" or "instances"

``` python
if link.rel in ('self', 'instances', 'create', 'update', 'destroy'):
    setattr(cls, '_{}'.format(link.rel), link)
else:
    links[link.rel] = link
```

**Comment by lyschoening** [comment]
You're right. This is fixed now.

Also, regarding our conversation yesterday, I've now added support for specifying subclasses of `Resource` with `Client.resource_factory()`. I've also added a helper function, `converter.schema_resolve_refs()`, to help resolve `{$ref}` objects that you might have in your JSON schemas.

**Comment by mbiokyle29** [comment]
:+1: Thanks!
