### ISSUE TITLE
PotionJSONEncoder still referencing `uri` incorrectly

### ISSUE THREAD

**Issue by mbiokyle29** [biosustain/potion-client#13]
Hey @lyschoening,

Are you tired of hearing from me yet! I think we are one tiny change away from perfect JSON encoding harmony. In the PotionJSONEncoder, when given an instance of `Reference`, it returns the `o.uri` which I think we decided in Gitter would not point to the uri anymore, instead it should be `o._uri`.

``` python
if isinstance(o, Reference):
      # FIXME if reference is not saved, save it first here
      return {"$ref": o._uri}
```

If I missed something, my apologies. I have been occupied with other things for awhile! Thanks for your continued help on all of this.

**Comment by lyschoening** [comment]
Hi @mbiokyle29, 

No worries. I've committed a change that implements this. Let me know that works for you, and if it does I'll release a new version. If you find anything else that needs changing in a certain way, consider opening a PR. It is easier for me if I can just look at a suggestion and merge it.

**Comment by mbiokyle29** [comment]
This works perfectly! I will PR anything else that I run into.
