### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion-client#3]
For an application here, I'd like to distribute a command line client that works with either Python 2 or Python 3 (for the broadest possible compatibility), and uses Potion-Client internally. 

Unfortunately, the Potion-Client code does make use of function annotations and has a few other Python 2-incompatible bits. @lyschoening What's your preference on how to support Python 2 here? Remove function annotations and put that info into docstrings? Use one of the Python 2 annotation libraries (which aren't that great...)? Something else?

(Preliminary tweaks make by @mbiokyle29 here, and can touch up for a PR as appropriate: https://github.com/refgenomics/potion-client/tree/python2-compat)

**Comment by lyschoening** [comment]
I've taken out the function annotations for now. The tests now pass in Python 2.7. I forgot about @mbiokyle29's solution so I did this independently, but it looks like we made essentially the same changes.

PS: Let me know what other issues you encounter in wrapping your own client around potion-client. I see a few places where we might be able to improve the code to make it easier for you to contribute. Also, possibly you might need to bundle your API schema/pre-generate the client? It looks like that could be implemented quite easily.

**Comment by boydgreenfield** [comment]
Perfect, thanks! @lyschoening – what do you suggest w/r/t pre-generating the client?

**Comment by lyschoening** [comment]
@boydgreenfield Depending on what is needed it would either be enough to just initialize the client with a file path to a downloaded schema, or there would be some minimal generation of the Python code for the classes if that is necessary. In either case there needs to be either a cli command for saving a schema or a route in Potion that contains the full schema.
