### ISSUE TITLE
Feature request: support authentication

### ISSUE THREAD

**Issue by ricardocabral** [biosustain/potion-client#6]
For example, how would I go about adding an http request argument (an API token for example) to every request made by the client?

**Comment by lyschoening** [comment]
Hi @ricardocabral. I am currently rewriting potion-client and planning to release it later this week. You can find it in the `new-potion-client` branch. If you use the version in that branch, you can authenticate like so:

``` python
# Basic auth:
client = Client('https://potion/api', auth=(USERNAME, PASSWORD))

# Bearer auth:
from potion_client.auth import HTTPBearerAuth
client = Client('https://potion/api', auth=HTTPBearerAuth(TOKEN))

```

http://docs.python-requests.org/en/master/user/authentication/

**Comment by lyschoening** [comment]
Hi @ricardocabral I just released the new version of the client.

**Comment by ricardocabral** [comment]
Thanks!
